name: Test iKite Dart
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repository
        uses: actions/checkout@v2

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1.3

      - name: cd to ikite-dart
        run: cd ikite-dart

      - name: Install Pub Dependencies
        run: dart pub get

      - name: Verify Formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze Project Source
        run: dart analyze

      - name: Run tests
        run: dart test